# Generated by Django 4.1.2 on 2023-02-18 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_auctionlist_date_time_alter_bid_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlist',
            name='date_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='date_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_time',
            field=models.DateTimeField(null=True),
        ),
    ]
