# Generated by Django 4.1.2 on 2023-02-18 22:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_auctionlist_date_time_alter_bid_date_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlist',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='date_time',
        ),
        migrations.AddField(
            model_name='auctionlist',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='bid',
            name='date_creted',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='comment',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
