# Generated by Django 4.1.2 on 2023-02-19 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_remove_auctionlist_date_time_remove_bid_date_time_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuctionList',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.DeleteModel(
            name='Bid',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
