# Generated by Django 4.1.2 on 2023-02-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auctionlist_comment_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlist',
            name='description',
            field=models.CharField(max_length=250),
        ),
    ]
