# Generated by Django 4.1.2 on 2023-02-21 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_alter_auctionlist_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlist',
            name='image',
            field=models.ImageField(upload_to='auctions/static/auctions/images'),
        ),
    ]
