# Generated by Django 4.1.2 on 2023-02-21 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_auctionlist_comment_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlist',
            name='image_name',
        ),
    ]
