# Generated by Django 4.1.2 on 2023-02-26 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0024_auctionlist_comment_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlist',
            name='actual_bid',
            field=models.IntegerField(null=True),
        ),
    ]
