# Generated by Django 4.1.2 on 2023-02-27 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0025_alter_auctionlist_actual_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlist',
            name='active',
            field=models.CharField(default='T', max_length=1),
        ),
    ]
